### ISSUE TITLE
New feature request:  Notes

### ISSUE THREAD

**Issue by rlyon** [rlyon/qhost#21]
@kmanalo has requested a new feature for displaying notes.  Need to:

1) Add the note tag parser.
2) Add note to the node object.
3) There should be a way to identify the note in standard output (default behavior).  Still unsure where to add this to the output.
4) The -N option will output the note in the expanded view.

**Comment by kmanalo** [comment]
Hi @rlyon , just wanted to let you know I'm still using qhost actively;  we actually benefited from the load colorization as I noticed a node that was inactive, and was able to diagnose it further.

**Comment by rlyon** [comment]
Hi @kmanalo, thanks for the kind remarks.  I'm sorry I couldn't get to this sooner.  The notes are now implemented, but I still need to work through building filters to get the behavior you were looking for when you had them in the states.  But this should be a good start.  If a node has a note it will show up as an asterisk to the left of the hostname

```text
NODE               OS      CPU GPU MEMTOT   MEMUSE   JOBS SLOT LOAD    STATE   
--------------------------------------------------------------------------------
node1              linux   12  0   23.5G    1.4G     0    0    0.0    | F       
node14             linux   12  0   23.5G    1.4G     0    0    0.0    |   D     
node150            linux   12  0   23.5G    8.1G     1    12   12.01  |     E   
node163            linux   12  0   23.5G    5.9G     4    12   12.0   |  O  E   
node164          * linux   12  0   23.5G    5.0G     1    12   12.0   |     E   
```

by using the ```-N``` option or ```-A``` (all) the note will show up with the other extended attributes.

```text
NODE               OS      CPU GPU MEMTOT   MEMUSE   JOBS SLOT LOAD    STATE   
--------------------------------------------------------------------------------
node1              linux   12  0   23.5G    1.4G     0    0    0.0    | F       
node14             linux   12  0   23.5G    1.4G     0    0    0.0    |   D     
node150            linux   12  0   23.5G    8.1G     1    12   12.01  |     E   
node163            linux   12  0   23.5G    5.9G     4    12   12.0   |  O  E   
node164          * linux   12  0   23.5G    5.0G     1    12   12.0   |     E   
                   Note        : Went down offline until tested
```

I haven't tagged the 1.4.0 release and won't until I add a couple more features so you can pull in and test the changes in master.

**Comment by rlyon** [comment]
Reopen until documented
